### PR TITLE
refactor: replace RuleType enum with a const (#539)

### PR DESCRIPTION
**Pull request by roger-schaer**
## Summary
This PR resolves https://github.com/quantizor/markdown-to-jsx/issues/539 by replacing the `RuleType` enum with a const object.

## Description
As mentioned & discussed in https://github.com/quantizor/markdown-to-jsx/issues/539, the current way of declaring the `RuleType` as an `enum` causes problems when using [isolatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules) in `tsconfig.json`.

The solution, as described [on the TypeScript website](https://www.typescriptlang.org/tsconfig/#isolatedModules), is to simply replace the `enum` with a simple object `const`, and declare a `type` based on its keys & values. Additional updates were needed to correctly use types (and not values) in the various interfaces defined for node types.

This worked correctly, but there were still issues when running tests using Jest with the modifications made in `index.tsx`. Therefore, an additional change was made in `index.cjs.tsx` in order to export the `RuleType` explicitly (as is done with the `compiler` function).

## Testing
Since the updated code is functionally equivalent to the existing version & all existing unit tests pass correctly, it was not clear what type of test could be added.

### CODE REVIEW

**Comment by quantizor** [comment]
> Hi @quantizor, just wanted to check if you would have time in the coming weeks to check out this PR, it would unblock some things on my end if this could be merged. Thanks in advance and have a nice summer!

Hey Roger! I will try to make time, thanks for the reminder. Lots going on personally at the moment.

**Comment by roger-schaer** [comment]
> > Hi @quantizor, just wanted to check if you would have time in the coming weeks to check out this PR, it would unblock some things on my end if this could be merged. Thanks in advance and have a nice summer!
> 
> Hey Roger! I will try to make time, thanks for the reminder. Lots going on personally at the moment.

No worries, thank you for your answer and your help!

**Comment by zivkovicn** [comment]
@quantizor hello, any plans in merging this? thanks

**Review by quantizor — APPROVED** [review]
Thank you for doing this and apologies it took me some time to circle back to it.

**Comment by roger-schaer** [comment]
Thanks a lot @quantizor, I tested it now and it works perfectly with the new version!

**Pull request merged**
